version       = "0.1.0"
author        = "Dangel"
description   = "Nim cryptography facade for Kyber, ECC signatures, KCDSA, EC-KCDSA, and curve primitives."
license       = "MIT"
srcDir        = "src"

requires "nim >= 2.0.0"

task test, "Run the test suite":
  exec "nim c -r --path:src --nimcache:build/nimcache_core tests/test_core.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_kyber_math tests/test_kyber_math.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_kyber_polyvec tests/test_kyber_polyvec.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_kyber_indcpa tests/test_kyber_indcpa.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_kyber_kem tests/test_kyber_kem.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_field25519 tests/test_field25519.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_x25519 tests/test_x25519.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_sha2 tests/test_sha2.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_hmac tests/test_hmac.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_ecdsa_encoding tests/test_ecdsa_encoding.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_edsa tests/test_edsa.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_ed25519 tests/test_ed25519.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_secp256k1 tests/test_secp256k1.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_kcdsa_common tests/test_kcdsa_common.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_keccak tests/test_keccak.nim"
  exec "nim c -r --path:src --nimcache:build/nimcache_regression_properties tests/test_regression_properties.nim"
